id: P848E0C84
initial_creation_type: input
source_metadata:
  title: Works of Khenchen Sangye Phüntshog (vol. KHA)
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    2d9a:
      title: རྒྱུན་ཁྱེར་གྱི་བསངས་ཡིག་བསྡུས་པ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 2d9a.txt
      order: 1
    2a86:
      title: རྒྱལ་བ་རྡོ་རྗེ་འཆང་ཀུན་དགའ་བཟང་པོ་ལ་བསྟོད་ཅིང་གསོལ་བ་འདེབས་པ་བྱིན་རླབས་སྤྲིན་ཕུང་ཞེས་བྱ་བ་ལ།
        ཡན་ལག་བདུན་པ་ཕུལ་བའི་ཚིགས་བཅད་ལ། བླ་མ་ལ་གསོལ་འདེབས་ཕུར་ཚུགས་ལ། མཁན་ཆེན་ལྷུན་གྲུབ་དཔལ་ལྡན་ལ་བསྟོད་པ།
        ཤར་པ་ཡེ་ཤེས་བཟང་པོ་ལ་བསྟོད་པ་ལ་སོགས་པ་བསྟོད་པ་ཁག་མང་པོ་བཞུགས་སོ།།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 2a86.txt
      order: 2
    e03f:
      title: བདེ་མཆོག་མཁའ་འགྲོ་རྒྱ་མཚོའི་དབང་གི་བླ་མ་བརྒྱུད་པའི་གསོལ་འདེབས། བདེ་མཆོག་དྲིལ་བུ་པ་ས་ལུགས་ཀྱི་བརྒྱུད་པ།
        འཇིགས་བྱེད་རྭ་ལུགས་ཀྱི་བླ་མ་བརྒྱུད་པ། མཁའ་ལྡིང་གསེར་མིག་འཁྱིལ་བའི་བླ་མ་བརྒྱུད་པ།
        རྣམ་དག་དཀྱིལ་འཁོར་མའི་ཁ་བསྐོང་། རིགས་ལྔའི་ཁྱབ་བདག་མའི་ཁ་སྐོང་། ཚེ་དཔག་མེད་ལྷ་དགུ་ལ།
        ཀུན་རིག་ལ། ཀུན་ཁྱབ་འཁོར་ལོ་མའི་ཁ་སྐོང་། ལམ་ཟབ་བརྒྱུད་འདེབས་ཀྱི་ཁ་སྐོང་། བློ་སྦྱོང་དོན་བདུན་མའི་བརྒྱུད་འདེབས་བཅས་ལ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: e03f.txt
      order: 3
    6a98:
      title: གུ་རུ་མཚོ་སྐྱེས་རྡོ་རྗེ་ལ་གསོལ་བ་འདེབས་པའི་ཚིགས་བཅད། ངག་དབང་དབྱངས་ཅན་ལྷ་མོ་ལ་བསྟོད་པ་མངོན་རྟོགས་རབ་གསལ།
        རྡོ་རྗེ་འཆར་ཀུན་དགའ་བཟང་པོའི་ཕྱི་རྟེན་བདེ་གཤེགས་མཆོད་རྟེན་བརྒྱད་ཀྱིས་གཙོས་པའི་མཆོད་རྟེན་རྣམས་ལ་གསེར་ཁེབས་གསར་སྤོས་མཛད་སྐབས་བསྔགས་བརྗོད།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 6a98.txt
      order: 4
    90c2:
      title: བྷཊྚ་ར་ཀ་ཧ་སྱེ་བཛྲ་གྱིས་གསུང་ཟེར་འགའ་བདོག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 90c2.txt
      order: 5
    9afa:
      title: གྲགས་རྒྱལ་བླ་མའི་རྣལ་འབྱོར།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 9afa.txt
      order: 6
    4c82:
      title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་ཀྱི་སྒྲུབ་ཐབས་ཀྱི་རྣམ་པར་བཤད་པ་མཁའ་སྤྱོད་ལམ་བཟང་ཞེས་བྱ་བ་ལ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 4c82.txt
      order: 7
    17f9:
      title: དཔལ་ལྡན་བླ་མ་མཆོད་པའི་ཆོ་ག་མདོ་རྒྱུད་རྒྱ་མཚོའི་ཉིང་ཁུ་འཆི་བ་མེད་པའི་གོ་འཕང་སྦྱིན་པ་ཞེས་བྱ་བ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 17f9.txt
      order: 8
    163b:
      title: ལྟ་སྒོམ་འབེལ་གཏམ་བྱུང་བའི་བརྗེད་ཐོ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 163b.txt
      order: 9
    70d6:
      title: རྣལ་འབྱོར་མའི་ཀུ་སཱ་ལའི་ཚོགས་བསགས་ཀྱི་ངག་འདོན།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 70d6.txt
      order: 10
    3cd9:
      title: ནཱ་རོ་མཁའ་སྤྱོད་ཀྱི་འཕོ་བ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 3cd9.txt
      order: 11
    314e:
      title: རྣལ་འབྱོར་མར་ཉེར་མཁོའི་རེག་ཟིག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 314e.txt
      order: 12
    e87a:
      title: རྗེ་བཙུན་རྣལ་འབྱོར་མའི་བསྟོད་གསོལ་བྱིན་རླབས་མྱུར་འཇུག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: e87a.txt
      order: 13
    09e6:
      title: རྣལ་འབྱོར་མའི་སྔགས་དོན་ལ་གནས་བརྟན་འཇམ་དབྱངས་གྲགས་པའི་གསུང་ལན།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 09e6.txt
      order: 14
    af61:
      title: གནས་ལུགས་སྒོམ་པའི་ལྷན་ཐབས་ཡིད་ཀྱི་མུན་སེལ་བི་ཛ་ཧ་ར།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: af61.txt
      order: 15
    e5ae:
      title: འཁྲིད་ཀྱི་སྙིང་པོ་གནས་ལུགས་གཅེར་མཐོང་གི་མན་ངག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: e5ae.txt
      order: 16
    3ca9:
      title: རྒད་པོ་མཛུབ་བཙུགས་ཀྱི་གདམས་ངག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 3ca9.txt
      order: 17
    082c:
      title: ཀྱེ་རྡོར་མངོན་རྟོགས་ལམ་དུས་ལ་ཉེ་བར་མཁོ་བའི་ཟིན་བྲིས།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 082c.txt
      order: 18
    f782:
      title: གཞལ་ཡས་ཁང་གི་ཕྱག་ཚད་མདོར་བསྡུས།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: f782.txt
      order: 19
    9d95:
      title: དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་སྒྲུབ་ཐབས་བདུད་འཇོམས་སྣང་བའི་གོ་དོན་བདུད་རྩིའི་ཉིང་ཁུ་ལ།
        ༠༢༡ རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་རྣམ་བཤད་རྡོ་རྗེ་མྱུ་གུ་ལས་གནད་དོན་རགས་པ་བསྡུས་པ་ལ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 9d95.txt
      order: 20
    4dac:
      title: སྐྱེར་སྒང་ལུགས་ཀྱི་ཡི་གེ་དྲུག་པའི་ཉེར་མཁོ་ཅུང་ཟད་གཅིག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 4dac.txt
      order: 21
    72e5:
      title: འཇམ་དཔལ་དཀར་པོ་དཔའ་བོ་གཅིག་སྒྲུབ་ཀྱི་ཆོས་སྐོར་བློ་གྲོས་པདྨོ་ཁ་འབྱེད།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 72e5.txt
      order: 22
    0ad2:
      title: འཇམ་དཔལ་དཀར་པོ་དཔའ་བོ་གཅིག་སྒྲུབ་ཀྱི་ཆོས་སྐོར་བློ་གྲོས་པདྨོ་ཁ་འབྱེད་ལས།
        སྒྲུབ་པའི་སྐབས་ཀྱི་ཆོ་ག་ཡེ་ཤེས་རབ་རྒྱས།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 0ad2.txt
      order: 23
    5cc0:
      title: གཏོར་བསྔོ་བརྒྱ་རྩ་སོགས་བྱེད་པའི་ཕྱག་ལེན་འདོད་དོན་ལྷུན་གྲུབ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 5cc0.txt
      order: 24
    f09e:
      title: ཐུགས་རྗེ་ཆེན་པོའི་དམར་ཁྲིད་ཐོ་ཡིག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: f09e.txt
      order: 25
    8e8e:
      title: ཐུགས་རྗེ་ཆེན་པོའི་དམར་ཁྲིད་ངེས་དོན་དཔྱིད་ཀྱི་ཐིག་ལེ་ལ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 8e8e.txt
      order: 26
    89b6:
      title: སྤྱན་རས་གཟིགས་ལ་ཡན་ལག་བདུན་པ་ཕུལ་བའི་ཚིགས་བཅད་དང་། གདུང་དབྱངས་གསོལ་འདེབས།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 89b6.txt
      order: 27
    e3dd:
      title: ཐུགས་རྗེ་ཆེན་པོ་སྤྱན་རས་གཟིགས་ཀྱི་སྦྱིན་སྲེག་གི་ཆོ་ག་འཕྲིན་ལས་རབ་རྒྱས།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: e3dd.txt
      order: 28
    a008:
      title: གཙུག་ཏོར་རྣམ་རྒྱལ་གྱི་སྦྱིན་སྲེག་གི་ཐོ་ཡིག་འཆི་མེད་འོད་སྣང་།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: a008.txt
      order: 29
    3eb3:
      title: དཔལ་རྡོ་རྗེ་ནག་པོ་ཆེན་པོ་གུར་གྱི་མགོན་པོའི་སྲུང་བ་རྡོ་རྗེའི་བྲག་རྫོང་མའི་འཁྲིད་ཉམས་སུ་བླང་ཚུལ་གྱི་བརྗེད་བྱང་བདུད་དཔུང་ཚར་གཅོད་ལ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 3eb3.txt
      order: 30
    c5da:
      title: དཔལ་གུར་གྱི་མགོན་པོའི་སྲུང་འཁོར་རྡོ་རྗེ་བྲག་རྫོང་མ་ལ་བརྟེན་པའི་བསྙེན་པའི་ཁ་སྐོང་ཞི་བའི་སྦྱིན་སྲེག་གི་ཐོ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: c5da.txt
      order: 31
    edad:
      title: མཁའ་འགྲོ་རྒྱ་མཚོའི་དབང་གི་དངོས་གཞིའི་སྡོམ་ལ།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: edad.txt
      order: 32
    7dc4:
      title: གསུང་ངག་རིན་པོ་ཆེ་ལམ་འབྲས་བུ་དང་བཅས་པའི་ཁྲིད་འཆད་པར་ཐོ་ཡིག་གནད་ཀྱི་ལྡེ་མིག
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 7dc4.txt
      order: 33
    e7e9:
      title: ལམ་འབྲས་འཆད་སྐབས་ཀྱི་ཐོ་ཆུང་།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: e7e9.txt
      order: 34
    7b01:
      title: དཔལ་མཁའ་འགྲོ་རྒྱ་མཚོའི་ཞི་བའི་སྦྱིན་སྲེག་མེ་ཤེལ་རབ་འབར།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 7b01.txt
      order: 35
    cc08:
      title: བདག་མེད་མའི་སྒྲུབ་དཀྱིལ་གྱི་ཐོ་ཡིག་ཐམས་ཅད་མཁྱེན་པ་དཀོན་མཆོག་ལྷུན་གྲུབ་ཀྱིས་མཛད་པའི་གསལ་བྱེད།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: cc08.txt
      order: 36
    69f7:
      title: འཇིགས་བྱེད་ས་ལུགས་ཀྱི་ཟུར་འདེབས་དང་པོའི་ལས་ཅན་དགའ་བྱེད།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 69f7.txt
      order: 37
    fffb:
      title: གུར་རིགས་བསྡུས་ཀྱི་དབང་གི་མཚམས་སྦྱོར།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: fffb.txt
      order: 38
    e821:
      title: པཎ་ཆེན་ནམ་མཁའ་དཔལ་བཟང་གིས་མཛད་པའི་གུར་གྱི་མགོན་པོ་ལྷ་བཅུ་གཉིས་ཀྱི་ཆོ་གའི་ཐོ་ཡིག་ཉིན་བྱེད་སྣང་བ་ལ་བརྟེན་ནས་གྲི་གུག་ལྷ་ལྔ་སིནྡྷུ་ར་ལ་བརྟེན་པ་སྙན་བརྒྱུད་ལུགས་དང་།
        མགོན་པོ་ལྷ་བཅུ་བདུན་གྱི་དབང་གི་ཕྱག་ལེན་ཟུར་འདེབས།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: e821.txt
      order: 39
    69bd:
      title: རྒྱལ་ཀུན་གསུང་རབ་སྙིང་པོ་མཁའ་འགྲོ་ཡི།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 69bd.txt
      order: 40
    7e20:
      title: རིགས་བརྒྱའི་ཁྱབ་བདག་རྒྱལ་བ་རྡོ་རྗེ་འཆང་བཅས་བཞུགས་སོ།།
      author: མཁན་ཆེན་སངས་རྒྱས་ཕུན་ཚོགས།
      base_file: 7e20.txt
      order: 41
created_at: '2022-04-06T17:09:12.422002'
last_modified_at: '2022-04-06T17:09:12.422012'
